mybatis:
  type-aliases-package: org.github.mybatis.spring.model
  mapper-locations: classpath:mapper/*.xml
spring:
  datasource:
    username: worker
    password: devworker
    url: jdbc:mysql://10.3.246.100:3306/test?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    hikari:
      pool-name: hikari-conn-pool
      maximum-pool-size: 30
      minimum-idle: 5
      idle-timeout: 180000
      connection-test-query: SELECT 1
      connection-timeout: 30000
logging:
  level:
    org.github.mybatis.spring.mapper: debug